[general]
import = ["~/AppData/Roaming/alacritty/rose-pine-default.toml"]
live_config_reload = true

[font]
normal = { family = "AtkynsonMono Nerd Font", style = "Regular" }
size = 14

[cursor]
style = { shape = "Beam", blinking = "On" }

[terminal]
shell = { program = "C:/Program Files/PowerShell/7/pwsh", args = ["-NoLogo"] }
#shell = "C:/Program Files/PowerShell/7/pwsh"